import enum

class UploadFileType(str, enum.Enum):
    PAYMENTS = "PAYMENTS"
    SETTLEMENTS = "SETTLEMENTS"
    FEES = "FEES"

class UploadStatus(str, enum.Enum):
    UPLOADED = "UPLOADED"
    VALIDATED = "VALIDATED"
    FAILED = "FAILED"

class RunStatus(str, enum.Enum):
    CREATED = "CREATED"
    PROCESSING = "PROCESSING"
    COMPLETED = "COMPLETED"
    FAILED = "FAILED"

class ExceptionType(str, enum.Enum):
    AMOUNT_MISMATCH = "AMOUNT_MISMATCH"
    MISSING_SETTLEMENT = "MISSING_SETTLEMENT"
    DUPLICATE = "DUPLICATE"
    REFERENCE_MISMATCH = "REFERENCE_MISMATCH"
    UNKNOWN = "UNKNOWN"

class ExceptionStatus(str, enum.Enum):
    OPEN = "OPEN"
    INVESTIGATING = "INVESTIGATING"
    AUTO_RESOLVED = "AUTO_RESOLVED"
    HUMAN_REVIEW = "HUMAN_REVIEW"
    REJECTED = "REJECTED"

class DecisionOutcome(str, enum.Enum):
    AUTO_RESOLVE = "AUTO_RESOLVE"
    HUMAN_REVIEW = "HUMAN_REVIEW"
    APPROVED = "APPROVED"
    REJECTED = "REJECTED"

class AuditAction(str, enum.Enum):
    FILE_UPLOADED = "FILE_UPLOADED"
    RECONCILIATION_STARTED = "RECONCILIATION_STARTED"
    RECONCILIATION_COMPLETED = "RECONCILIATION_COMPLETED"
    EXCEPTION_CREATED = "EXCEPTION_CREATED"
    AI_INVESTIGATION_COMPLETED = "AI_INVESTIGATION_COMPLETED"
    AUTO_RESOLVED = "AUTO_RESOLVED"
    SENT_TO_REVIEW = "SENT_TO_REVIEW"
    HUMAN_APPROVED = "HUMAN_APPROVED"
    HUMAN_REJECTED = "HUMAN_REJECTED"
